// Generated by https://pagedraw.io/pages/9526
import Post from './post';
import React from 'react';
import './content_pane.css';

function render() {
    return <div className="content_pane-content_pane-7">
        <div className="content_pane-0">
            <div className="content_pane-0-0">
                { this.props.posts.map((elem, i) => {
                    return <div key={i} className="content_pane-rectangle_3">
                        <div className="content_pane-0-0-0-0-0">
                            <div className="content_pane-post_instance-8">
                                <Post name={elem.name} date={elem.date} content={elem.content} onClickPost={elem.onClickPost} onChangeText={elem.onChangeText} comments={elem.comments} /> 
                            </div>
                        </div>
                    </div>;
                }) }
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}