// Generated by https://pagedraw.io/pages/9526
import React from 'react';
import './content.css';

function render() {
    return <div className="content-content-8">
        <div className="content-0">
            <div className="content-rectangle_2">
                <div className="content-0-0-0">
                    <div className="content-text_4">{ this.props.name }</div>
                    <div className="content-text_5">{ this.props.date }</div>
                </div>
                <div className="content-0-0-1">
                    <div className="content-text_6">
                        { this.props.content }
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}