// Generated by https://pagedraw.io/pages/9526
import React from 'react';
import './navbar.css';

function render() {
    return <div className="navbar-navbar-0">
        <div className="navbar-0">
            <div className="navbar-text_8">Facester</div>
            <div className="navbar-text_2">Logout</div>
        </div>
        <div className="navbar-1">
            <div className="navbar-line-9" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}