// Generated by https://pagedraw.io/pages/9526
import Content from './content';
import Text_area from './text_area';
import React from 'react';
import './post.css';

function render() {
    return <div className="post-post-5">
        <div className="post-0">
            <div className="post-content_instance-6">
                <Content name={this.props.name} date={this.props.date} content={this.props.content} /> 
            </div>
        </div>
        <div className="post-1">
            { (!!this.props.comments) ?
                <div className="post-1-0-0">
                    { this.props.comments.map((elem, i) => {
                        return <div key={i} className="post-rectangle_6">
                            <div className="post-1-0-0-0-0-0">
                                <div className="post-content_instance_2">
                                    <Content name={elem.name} date={elem.date} content={elem.content} /> 
                                </div>
                            </div>
                        </div>;
                    }) }
                </div>
            : null}
        </div>
        <div className="post-2">
            <div className="post-text_area_instance-2">
                <Text_area onClickPost={this.props.onClickPost} onChangeText={""} /> 
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}