// Generated by https://pagedraw.io/pages/9526
import React from 'react';
import './sidebar_row.css';

function render() {
    return <div className="sidebar_row-sidebar_row-4">
        <div className="sidebar_row-0">
            <div className="sidebar_row-0-0">
                <div className="sidebar_row-0-0-0">
                    <img src="https://ucarecdn.com/7fedf450-1c8b-4dd9-894a-269d03777867/" className="sidebar_row-image-4" /> 
                </div>
            </div>
            <div className="sidebar_row-text_3">
                { this.props.content }
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}