// Generated by https://pagedraw.io/pages/9526
import React from 'react';
import './sidebar_header.css';

function render() {
    return <div className="sidebar_header-sidebar_header-0">
        <div className="sidebar_header-0">
            <div className="sidebar_header-text_3">
                { this.props.title }
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}