// Generated by https://pagedraw.io/pages/9526
import Sidebar_header from './sidebar_header';
import Sidebar_row from './sidebar_row';
import React from 'react';
import './sidebar.css';

function render() {
    return <div className="sidebar-sidebar-6">
        <div className="sidebar-0">
            <div className="sidebar-rectangle-9">
                <div className="sidebar-0-0-0">
                    <div className="sidebar-0-0-0-0">
                        <div className="sidebar-0-0-0-0-0">
                            <div className="sidebar-sidebar_header_instance-2">
                                <Sidebar_header title={"Welcome!"} /> 
                            </div>
                        </div>
                        <div className="sidebar-0-0-0-0-1">
                            <div onClick={() => this.props.onChangeRoute("Home")} className="sidebar-sidebar_row_instance-1">
                                <Sidebar_row content={"Home"} /> 
                            </div>
                        </div>
                        <div className="sidebar-0-0-0-0-2">
                            <div onClick={() => this.props.onChangeRoute("Profile")} className="sidebar-sidebar_row_instance-9">
                                <Sidebar_row content={"Profile"} /> 
                            </div>
                        </div>
                        <div className="sidebar-0-0-0-0-3">
                            <div onClick={() => this.props.onChangeRoute("Settings")} className="sidebar-sidebar_row_instance-5">
                                <Sidebar_row content={"Settings"} /> 
                            </div>
                        </div>
                        <div className="sidebar-0-0-0-0-4">
                            <div className="sidebar-sidebar_header_instance-8">
                                <Sidebar_header title={"Settings"} /> 
                            </div>
                        </div>
                        <div className="sidebar-0-0-0-0-5">
                            <div className="sidebar-sidebar_row_instance-3">
                                <Sidebar_row content={"Payments"} /> 
                            </div>
                        </div>
                        <div className="sidebar-0-0-0-0-6" /> 
                        <div className="sidebar-0-0-0-0-7">
                            <div className="sidebar-sidebar_row_instance_2">
                                <Sidebar_row content={"Logout"} /> 
                            </div>
                        </div>
                    </div>
                    <div className="sidebar-line_2" /> 
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}