// Generated by https://pagedraw.io/pages/9526
import React from 'react';
import './text_area.css';

function render() {
    return <div className="text_area-text_area-6">
        <div className="text_area-0">
            <div className="text_area-comment_button-5">
                <div className="text_area-0-0-0">
                    <textarea placeholder="Placeholder" onChange={this.props.onChangeText} className="text_area-text_input-3" /> 
                </div>
                <div className="text_area-0-0-1">
                    <div onClick={this.props.onClickPost} className="text_area-rectangle_5">
                        <div className="text_area-0-0-1-0-0">
                            <div className="text_area-text_7">Post</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}